name: essayguru
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  responsive_framework: ^0.1.7
  rxdart: ^0.28.0
  essayguru_ui_components:
    path: C:\Users\Public\Engineer\projects\essayguru_ui_components

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
